=== SFBB/gallery/tools/experience.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://tools.gallery.any.coop/experience.schema.json",
  "title": "Anytype Experience",
  "description": "Experience shared in Anytype Gallery",
  "type": "object",
  "properties": {
    "id": {
      "description": "The unique identifier for an experience",
      "type": "string"
    },
    "name": {
      "type": "string",
      "title": "Name/identifier",
      "pattern": "^[a-z0-9-][a-z0-9-_]*$",
      "maxLength": 255,
      "minLength": 2,
      "description": "The experience's name will be used internally as a folder name in the Gallery."
    },
    "author": {
      "$ref": "#/$defs/githubLink",
      "title": "Author",
      "description": "A person currently contributing the most to the experience."
    },
    "license": {
      "const": "MIT",
      "title": "License",
      "description": "Currently only MIT is accepted, although more licenses will be available after alpha."
    },
    "title": {
      "type": "string",
      "title": "Title",
      "pattern": "^[^\\s]+(?: [^\\s]+)*$",
      "maxLength": 255,
      "minLength": 2,
      "description": "The experience title will be displayed in the Gallery."
    },
    "description": {
      "type": "string",
      "title": "Description",
      "pattern": "^[^\\s]+(\\s+[^\\s]+)*$",
      "maxLength": 2048,
      "minLength": 16,
      "description": "It helps people understand what the experience provides. It will be displayed in the Gallery."
    },
    "screenshots": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/link"
      },
      "title": "Screenshots",
      "minItems": 1,
      "description": "Screenshots of the experience. They will be displayed in the Gallery.",
      "uniqueItems": true
    },
    "downloadLink": {
      "$ref": "#/$defs/link",
      "title": "Download link",
      "description": "The link to the experience's download file."
    },
    "fileSize": {
      "type": "integer",
      "title": "File size",
      "description": "The size of the experience's download file in bytes."
    },
    "categories": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/category"
      },
      "minItems": 1,
      "description": "Categories help people find the Experience. They will be displayed in the Gallery.",
      "uniqueItems": true
    },
    "contributors": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/githubLink"
      },
      "title": "Contributors",
      "minItems": 0,
      "description": "People who have meaningfully contributed to the experience.",
      "uniqueItems": true
    },
    "language": {
      "type": "string",
      "default": "en-US",
      "enum": [
        "ach-UG", "aa-ER", "af-ZA", "ak-GH", "tw-TW", "sq-AL",
        "am-ET", "ar-SA", "ar-BH", "ar-EG", "ar-YE",
        "an-ES", "hy-AM", "frp-IT", "as-IN", "ast-ES", "tay-TW",
        "av-DA", "ae-IR", "ay-BO", "az-AZ", "ban-ID", "bal-BA",
        "bm-ML", "ba-RU", "eu-ES", "be-BY", "bn-BD", "bn-IN",
        "ber-DZ", "bh-IN", "bfo-BF", "bi-VU", "bs-BA", "br-FR",
        "bg-BG", "my-MM", "ca-ES", "ceb-PH", "ch-GU", "ce-CE",
        "chr-US", "ny-MW", "zh-CN", "zh-TW", "zh-HK", "zh-MO",
        "zh-SG", "cv-CU", "kw-GB", "co-FR", "cr-NT", "hr-HR",
        "cs-CZ", "da-DK", "fa-AF", "dv-MV", "nl-NL", "nl-BE",
        "nl-SR", "dz-BT", "en-US", "en-UD", "en-AR", "en-AU",
        "en-BZ", "en-CA", "en-CB", "en-CN", "en-DK", "en-HK",
        "en-IN", "en-ID", "en-IE", "en-JM", "en-JA", "en-MY",
        "en-NZ", "en-NO", "en-PH", "en-PR", "en-SG", "en-ZA",
        "en-SE", "en-GB", "en-ZW", "eo-UY", "et-EE",
        "ee-GH", "fo-FO", "fj-FJ", "fil-PH", "fi-FI", "vls-BE",
        "fra-DE", "fr-FR", "fr-BE", "fr-CA", "fr-LU", "fr-QC",
        "fr-CH", "fy-NL", "fur-IT", "ff-ZA", "gaa-GH", "gl-ES",
        "ka-GE", "de-DE", "de-AT", "de-BE", "de-LI", "de-LU",
        "de-CH", "got-DE", "el-GR", "el-CY", "kl-GL", "gn-PY",
        "gu-IN", "ht-HT", "ha-HG", "haw-US", "he-IL", "hz-NA",
        "hil-PH", "hi-IN", "ho-PG", "hmn-CN", "hu-HU", "is-IS",
        "io-EN", "ig-NG", "ilo-PH", "id-ID", "iu-NU", "ga-IE",
        "it-IT", "it-CH", "ja-JP", "jv-ID", "quc-GT", "kab-KAB",
        "kn-IN", "pam-PH", "ks-IN", "ks-PK", "csb-PL", "kk-KZ",
        "km-KH", "rw-RW", "tlh-AA", "kv-KO", "kg-CG", "kok-IN",
        "ko-KR", "ku-TR", "kmr-TR", "kj-AO", "ky-KG", "lol-US",
        "lo-LA", "la-LA", "lv-LV", "lij-IT", "li-LI", "ln-CD",
        "lt-LT", "jbo-EN", "nds-DE", "dsb-DE", "lg-UG", "luy-KE",
        "lb-LU", "mk-MK", "mai-IN", "mg-MG", "ms-MY", "ms-BN",
        "ml-IN", "mt-MT", "gv-IM", "mi-NZ", "arn-CL", "mr-IN",
        "mh-MH", "moh-CA", "mn-MN", "sr-Cyrl-ME", "me-ME", "mos-MOS",
        "na-NR", "ng-NA", "ne-NP", "ne-IN", "pcm-NG", "se-NO",
        "ns-ZA", "no-NO", "nb-NO", "nn-NO", "oc-FR", "or-IN",
        "oj-CA", "om-ET", "os-SE", "pi-IN", "pap-PAP", "ps-AF",
        "fa-IR", "en-PT", "pl-PL", "pt-PT", "pt-BR", "pa-IN",
        "pa-PK", "qu-PE", "qya-AA", "ro-RO", "rm-CH", "rn-BI",
        "ru-RU", "ru-BY", "ru-MD", "ry-UA", "ru-UA", "sah-SAH",
        "sg-CF", "sa-IN", "sat-IN", "sc-IT", "sco-GB", "gd-GB",
        "sr-SP", "sr-CS", "sh-HR", "crs-SC", "sn-ZW", "ii-CN",
        "sd-PK", "si-LK", "sk-SK", "sl-SI", "so-SO", "son-ZA",
        "ckb-IR", "nr-ZA", "sma-NO", "st-ZA", "es-ES", "es-EM",
        "es-AR", "es-BO", "es-CL", "es-CO", "es-CR", "es-DO", "es-EC",
        "es-SV", "es-GT", "es-HN", "es-419", "es-MX", "es-NI",
        "es-PA", "es-PY", "es-PE", "es-PR", "es-US", "es-UY",
        "es-VE", "su-ID", "sw-KE", "sw-TZ", "ss-ZA",
        "sv-SE", "sv-FI", "syc-SY", "tl-PH", "ty-PF", "tg-TJ",
        "tzl-TZL", "ta-IN", "tt-RU", "te-IN", "kdh-KDH", "th-TH",
        "bo-BT", "ti-ER", "ts-ZA", "tn-ZA", "tr-TR", "tr-CY",
        "tk-TM", "uk-UA", "hsb-DE", "ur-IN", "ur-PK", "ug-CN",
        "uz-UZ", "val-ES", "ve-ZA", "vec-IT", "vi-VN", "wa-BE",
        "cy-GB", "wo-SN", "xh-ZA", "yi-DE", "yo-NG", "zea-ZEA", "zu-ZA"
      ]
    }
  },
  "required": [ "id", "author", "license", "title", "description", "categories", "screenshots", "downloadLink" ],
  "$defs": {
    "link": {
      "type": "string",
      "pattern": "^(http(s?):\\/\\/)?(www\\.)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?$",
      "maxLength": 255,
      "minLength": 2
    },
    "githubLink": {
      "type": "string",
      "pattern": "^(http(s?):\\/\\/)?(www\\.)?github\\.([a-z])+\\/([A-Za-z0-9_-]{1,})+\\/?$",
      "maxLength": 75,
      "minLength": 2
    },
    "category": {
      "type": "string",
      "enum": [
        "Collaboration",
        "Dashboard",
        "Work",
        "Education",
        "Personal Growth",
        "Project tracking",
        "Collection",
        "Health & Fitness",
        "Finance",
        "Food & Nutrition",
        "Travel",
        "Hobbies",
        "Home",
        "Other"
      ]
    }
  }
}

=== SFBB/gallery/experiences/para_tasks_resources_meeting_notes_crm/test-manifest.json
{
  "$schema": "https://tools.gallery.any.coop/experience.schema.json",
  "id": "42e81ea8-021f-4426-91b6-0a2a46866bc8",
  "name": "para_tasks_resources_meeting_notes_crm",
  "author": "https://github.com/ChristianHaake",
  "license": "MIT",
  "title": "PARA / Tasks / Resources / Meeting notes / CRM",
  "description": "Here is my fully integrated space. Where I embrace the PARA Methodology. This Space includes the following aspects:\n\n- PARA\r\n- Meeting notes \r\n- CRM\r\n- Library \r\n- Wiki\r\n- Tasks and Projects\n\nFor in detail explanation, check out my articles:\r\n- https://haak3.de/articles/2023_Anytype/2023_Anytype-Dashboard/2023_Anytype-Dashboard-EN.html\r\n- https://haak3.de/articles/2023_Anytype/2023_Anytype-Meetingnotes/2023_Antype-Meetingnotes-EN.html\r\n- https://haak3.de/articles/2023_Anytype/2023_Mein-PKM_mit-CODE/2023_MY-PKM-with-Code.html\r\n- https://haak3.de/articles/2023_Anytype/2023_Anytype-mit-PARA/2023_Using-PARA-with-Anytype-EN.html",
  "categories": [
    "Dashboard",
    "Work",
    "Education",
    "Project tracking",
    "Hobbies"
  ],
  "language": "en-US",
  "screenshots": [
    "https://github.com/anyproto/gallery/raw/para_tasks_resources_meeting_notes_crm/experiences/para_tasks_resources_meeting_notes_crm/screenshots/screenshot-1.png",
    "https://github.com/anyproto/gallery/raw/para_tasks_resources_meeting_notes_crm/experiences/para_tasks_resources_meeting_notes_crm/screenshots/screenshot-2.png",
    "https://github.com/anyproto/gallery/raw/para_tasks_resources_meeting_notes_crm/experiences/para_tasks_resources_meeting_notes_crm/screenshots/screenshot-3.png",
    "https://github.com/anyproto/gallery/raw/para_tasks_resources_meeting_notes_crm/experiences/para_tasks_resources_meeting_notes_crm/screenshots/screenshot-4.png",
    "https://github.com/anyproto/gallery/raw/para_tasks_resources_meeting_notes_crm/experiences/para_tasks_resources_meeting_notes_crm/screenshots/screenshot-5.png"
  ],
  "downloadLink": "https://github.com/anyproto/gallery/raw/para_tasks_resources_meeting_notes_crm/experiences/para_tasks_resources_meeting_notes_crm/para_tasks_resources_meeting_notes_crm.zip",
  "fileSize": 8068542
}
